(()=>{"use strict";
function start(){
const d=document,b=d.body,r=d.documentElement;if(!b||r.dataset.researchFluid==="1"||matchMedia("(hover:none),(pointer:coarse)").matches)return;r.dataset.researchFluid="1";
const reduce=matchMedia("(prefers-reduced-motion:reduce)").matches,targets=[];
const hero=d.querySelector(".paper-hero");if(hero)targets.push(hero);
if(b.dataset.page==="home"||b.dataset.page==="papers")targets.push(...d.querySelectorAll(".sequence-row"));
if(!targets.length)return;
const clean=s=>(s||"").replace(/\s+/g," ").trim(),NS="http://www.w3.org/2000/svg";
function titleOf(t){return clean(t.querySelector("h1,.sequence-title,h2,h3")?.textContent)||"The Proper Ending Index"}
function metaOf(t){return clean(t.querySelector(".paper-meta,.sequence-meta,.record-row,.eyebrow")?.textContent)||"Working paper · v6.2 · preserved research record"}
function paper(title,meta){let p=d.createElement("div");p.className="research-paper";let k=d.createElement("p");k.className="research-paper-kicker";k.textContent="THE PROPER ENDING INDEX / PRESERVED RESEARCH RECORD";let h=d.createElement("div");h.className="research-paper-title";h.textContent=title;let m=d.createElement("div");m.className="research-paper-meta";m.textContent=meta;let lines=d.createElement("div");lines.className="research-paper-lines";for(let i=0;i<26;i++)lines.append(d.createElement("i"));p.append(k,h,m,lines);return p}
function liquidFilter(i){let svg=d.createElementNS(NS,"svg");svg.setAttribute("width","0");svg.setAttribute("height","0");svg.setAttribute("aria-hidden","true");svg.classList.add("research-filter-defs");let defs=d.createElementNS(NS,"defs"),f=d.createElementNS(NS,"filter"),turb=d.createElementNS(NS,"feTurbulence"),disp=d.createElementNS(NS,"feDisplacementMap");let id=`research-liquid-${i}`;f.id=id;f.setAttribute("x","-22%");f.setAttribute("y","-22%");f.setAttribute("width","144%");f.setAttribute("height","144%");turb.setAttribute("type","fractalNoise");turb.setAttribute("baseFrequency","0.011 0.026");turb.setAttribute("numOctaves","2");turb.setAttribute("seed",String(11+i*7));turb.setAttribute("result","noise");disp.setAttribute("in","SourceGraphic");disp.setAttribute("in2","noise");disp.setAttribute("scale","22");disp.setAttribute("xChannelSelector","R");disp.setAttribute("yChannelSelector","B");f.append(turb,disp);defs.append(f);svg.append(defs);b.append(svg);return{id,turb,disp}}
function mount(t,i){let membrane=d.createElement("div");membrane.className="research-membrane";membrane.setAttribute("aria-hidden","true");let base=paper(titleOf(t),metaOf(t)),refract=d.createElement("div"),clone=base.cloneNode(true),caustic=d.createElement("div"),rim=d.createElement("div");refract.className="research-refraction";caustic.className="research-caustic";rim.className="research-liquid-rim";let filter=reduce?null:liquidFilter(i);if(filter)clone.style.filter=`url(#${filter.id}) grayscale(.02) contrast(1.16) brightness(1.08)`;refract.append(clone);membrane.append(base,refract,caustic,rim);t.prepend(membrane);t.classList.add("has-research-membrane");if(reduce)return;
let px=0,py=0,pt=performance.now(),v=0,raf=0;
const move=e=>{if(e.pointerType==="touch")return;let box=t.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),y=Math.max(0,Math.min(1,(e.clientY-box.top)/box.height)),now=performance.now(),dx=e.clientX-px,dy=e.clientY-py,dt=Math.max(8,now-pt);v=Math.min(1,Math.hypot(dx,dy)/dt/1.05);px=e.clientX;py=e.clientY;pt=now;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;t.style.setProperty("--lx",(x*100).toFixed(2)+"%");t.style.setProperty("--ly",(y*100).toFixed(2)+"%");t.style.setProperty("--vx",Math.max(-26,Math.min(26,dx*.22)).toFixed(2)+"px");t.style.setProperty("--vy",Math.max(-20,Math.min(20,dy*.2)).toFixed(2)+"px");t.style.setProperty("--fluid-v",v.toFixed(3));if(filter){filter.disp.setAttribute("scale",(24+v*46).toFixed(1));filter.turb.setAttribute("baseFrequency",`${(.009+x*.008).toFixed(4)} ${(.019+y*.014).toFixed(4)}`)}t.classList.add("is-fluid-active")})};
const leave=()=>{t.classList.remove("is-fluid-active");t.style.setProperty("--fluid-v","0");t.style.setProperty("--vx","0px");t.style.setProperty("--vy","0px");if(filter)filter.disp.setAttribute("scale","22")};
t.addEventListener("pointermove",move,{passive:true});t.addEventListener("pointerleave",leave,{passive:true})}
targets.forEach(mount);
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();