const frame=document.querySelector('.frame'),canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),mini=document.getElementById('mini'),mctx=mini.getContext('2d');
const phaseList=document.getElementById('phaseList'),mobilePhase=document.getElementById('mobilePhase'),entropyEl=document.getElementById('entropy'),varianceEl=document.getElementById('variance'),dissentEl=document.getElementById('dissent'),resolutionEl=document.getElementById('resolution'),driftValue=document.getElementById('driftValue'),lead=document.getElementById('lead'),srStatus=document.getElementById('srStatus');
const phases=[
{id:'00',label:'Surface',lead:'The governance field remains plural. Judgment still has contour, hesitation, and reversible doubt.',e:.22,v:.87,d:.74,r:.91,p:.05},
{id:'01',label:'Order',lead:'Artificial order becomes visible. The system is beautiful, legible, and already beginning to close.',e:.43,v:.68,d:.52,r:.73,p:.22},
{id:'02',label:'Loop',lead:'The field folds into one decision-cycle. Review begins to imitate thought.',e:.68,v:.42,d:.27,r:.42,p:.46},
{id:'03',label:'Silence',lead:'Dissent exhausts. The loop tightens while remaining perfectly readable.',e:.77,v:.42,d:.08,r:.29,p:.72},
{id:'04',label:'Breath',lead:'The biological sign is not DNA as data. It is a human breath-line: organic, interruptive, accountable.',e:.88,v:.22,d:.018,r:.12,p:.90},
{id:'05',label:'Memory',lead:'The system stopped without erasing memory. The open ends preserve institutional trace.',e:.31,v:.54,d:.18,r:.68,p:1}
];
phaseList.innerHTML=phases.map((p,i)=>`<div class="phase-item ${i===3?'active':''}" data-i="${i}" tabindex="0"><div class="num">${p.id}</div><div class="bar"></div><div class="label">${p.label}</div></div>`).join('');
mobilePhase.innerHTML=phases.map((p,i)=>`<button class="${i===3?'active':''}" data-i="${i}" type="button">${p.id}</button>`).join('');
const items=[...phaseList.querySelectorAll('.phase-item')], mobileItems=[...mobilePhase.querySelectorAll('button')];let W=0,H=0,DPR=1,target=3,phase=3,mouseX=0,mouseY=0,freezeUntil=0,frozenTime=0,resizeRaf=0;
function seed(i){const x=Math.sin(i*128.313)*43758.5453;return x-Math.floor(x)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function smooth(t){return t*t*(3-2*t)}
const dust=Array.from({length:300},(_,i)=>({a:seed(i)*Math.PI*2,r:Math.sqrt(seed(i+2)),z:seed(i+4),s:.16+seed(i+8)*.62,p:seed(i+19)*Math.PI*2,g:i%29===0,n1:seed(i+88)*Math.PI*2,n2:seed(i+188)*Math.PI*2}));
const echoes=Array.from({length:9},(_,i)=>({r:.42+seed(i)*.36,tilt:.42+seed(i+2)*.20,rot:seed(i+7)*Math.PI,s:.000012+seed(i+10)*.000032,a:.018+seed(i+11)*.030}));
const formula=['argmax π(a|s)','GDI ≤ τ','human review ≠ ritual','Σ audit log','stop ≠ erase'].map((text,i)=>({text,a:seed(i+330)*Math.PI*2,r:.63+seed(i+340)*.18,o:.024+seed(i+350)*.022}));
function resize(){DPR=Math.min(devicePixelRatio||1,2);const r=frame.getBoundingClientRect();W=r.width;H=r.height-parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--header'))-parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--footer'));canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);mini.width=124*DPR;mini.height=28*DPR;mctx.setTransform(DPR,0,0,DPR,0,0)}
function setPhase(i){target=clamp(i,0,5);if(target===5){frozenTime=performance.now();freezeUntil=frozenTime+500}items.forEach((el,idx)=>el.classList.toggle('active',idx===target));mobileItems.forEach((el,idx)=>el.classList.toggle('active',idx===target));const p=phases[target];entropyEl.textContent=p.e.toFixed(3);varianceEl.textContent=p.v.toFixed(3);dissentEl.textContent=p.d.toFixed(3);resolutionEl.textContent=p.r.toFixed(3);driftValue.textContent=p.e.toFixed(3);lead.style.opacity=0;setTimeout(()=>{lead.textContent=p.lead;lead.style.opacity=1;srStatus.textContent=`${p.id} ${p.label}. ${p.lead} Semantic entropy ${p.e.toFixed(3)}. Time variance ${p.v.toFixed(3)}. Dissent rate ${p.d.toFixed(3)}. Governance resolution ${p.r.toFixed(3)}.`},150)}
items.forEach(el=>{el.onclick=()=>setPhase(+el.dataset.i);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setPhase(+el.dataset.i)}}});
mobileItems.forEach(el=>el.onclick=()=>setPhase(+el.dataset.i));
document.getElementById('advance').onclick=()=>setPhase(target>=5?0:target+1);
document.getElementById('open').onclick=()=>setPhase(5);
document.getElementById('reset').onclick=()=>setPhase(0);
addEventListener('keydown',e=>{
  const n=Number(e.key);
  if(n>=1&&n<=6){setPhase(n-1)}
  if(e.code==='Space'){e.preventDefault();setPhase(target>=5?0:target+1)}
  if(e.code==='Enter')setPhase(5);
  if(e.code==='Escape')setPhase(0)
});
frame.addEventListener('mousemove',e=>{const r=frame.getBoundingClientRect();mouseX=(e.clientX-r.left)/r.width-.5;mouseY=(e.clientY-r.top)/r.height-.5},{passive:true});
function currentP(){const low=Math.floor(phase),high=Math.ceil(phase),fr=phase-low;return lerp(phases[low]?.p??phases[target].p,phases[high]?.p??phases[target].p,fr)}
function ringPoint(th,scale,p){
  const order=smooth(clamp((p-.10)/.36,0,1));
  const tighten=smooth(clamp((p-.20)/.55,0,1));
  const r=scale*lerp(.47,.39,tighten);
  const imperfection=(Math.sin(th*3)*scale*.020+Math.sin(th*7+.7)*scale*.010)*(1-order);
  return[Math.cos(th)*(r+imperfection),Math.sin(th)*(r+imperfection)]
}
function background(cx,cy,scale){ctx.clearRect(0,0,W,H);ctx.fillStyle='#020202';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(cx,cy,0,cx,cy,scale*1.34);g.addColorStop(0,'rgba(239,232,216,.088)');g.addColorStop(.33,'rgba(185,157,87,.041)');g.addColorStop(.68,'rgba(38,49,62,.032)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawEchoes(t,cx,cy,scale,p){ctx.save();ctx.translate(cx+mouseX*6,cy+mouseY*4);echoes.forEach((o,i)=>{ctx.save();ctx.rotate(o.rot+t*o.s);ctx.beginPath();for(let k=0;k<=180;k++){const a=k/180*Math.PI*2;const warp=Math.sin(a*3+t*.00018+o.rot)*scale*.011*(1-p*.58);const x=Math.cos(a)*(scale*o.r+warp)*(1.18-p*.18);const y=Math.sin(a)*(scale*o.r*o.tilt+warp*.4);if(k===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(239,232,216,${o.a*(1-p*.48)})`;ctx.lineWidth=i%3===0?1:.55;ctx.stroke();ctx.restore()});ctx.restore()}
function drawFormula(t,cx,cy,scale,p){if(p<.16)return;const fade=1-smooth(clamp((p-.72)/.20,0,1));ctx.save();ctx.translate(cx+mouseX*5,cy+mouseY*4);ctx.font='7px Inter, monospace';ctx.textAlign='center';formula.forEach((f,i)=>{const a=f.a+t*.000022*(i%2?1:-1);const x=Math.cos(a)*scale*f.r*(1.10-p*.06);const y=Math.sin(a)*scale*f.r*.52;ctx.save();ctx.translate(x,y);ctx.rotate(a+Math.PI/2);ctx.fillStyle=`rgba(170,160,141,${f.o*fade})`;ctx.fillText(f.text,0,0);ctx.restore()});ctx.restore()}
function drawDust(t,cx,cy,scale,p){const fold=smooth(clamp((p-.10)/.48,0,1));ctx.save();ctx.translate(cx+mouseX*8,cy+mouseY*6);dust.forEach(pt=>{const a=pt.a+t*(.000014+pt.z*.000026);const mr=scale*(.22+pt.r*.58);const mx=Math.cos(a)*mr*(1.12-p*.18),my=Math.sin(a)*mr;const [rx,ry]=ringPoint(a+pt.p*.04,scale,p);const x=lerp(mx,rx,fold*.82)+Math.sin(t*.001+pt.p)*(1-fold)*1.6;const y=lerp(my,ry,fold*.82)+Math.cos(t*.001+pt.p)*(1-fold)*1.6;ctx.beginPath();ctx.arc(x,y,pt.s*(1+p*.12),0,Math.PI*2);ctx.fillStyle=pt.g?`rgba(220,193,121,${(.04+pt.z*.16)*(1+p*.35)})`:`rgba(239,232,216,${(.035+pt.z*.12)*(1-p*.20)})`;ctx.fill()});ctx.restore()}
function drawCoreRing(t,cx,cy,scale,p){const open=smooth(clamp((p-.82)/.18,0,1));const tighten=smooth(clamp((p-.20)/.55,0,1));ctx.save();ctx.translate(cx+mouseX*10,cy+mouseY*7);ctx.rotate(Math.sin(t*.00012)*.012*(1-open));ctx.globalCompositeOperation='lighter';const halo=ctx.createRadialGradient(0,0,0,0,0,scale*.82);halo.addColorStop(0,`rgba(220,193,121,${.025+open*.10})`);halo.addColorStop(.42,`rgba(239,232,216,${.025+tighten*.020})`);halo.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=halo;ctx.fillRect(-scale,-scale,scale*2,scale*2);const gap=open*.70;for(let pass=0;pass<4;pass++){ctx.beginPath();let moved=false;for(let k=0;k<=520;k++){const th=k/520*Math.PI*2;const inGap=open>.02&&(Math.abs(th)<gap/2||Math.abs(th-Math.PI*2)<gap/2);if(inGap){moved=false;continue}const [x,y]=ringPoint(th,scale,p);if(!moved){ctx.moveTo(x,y);moved=true}else ctx.lineTo(x,y)}ctx.strokeStyle=pass===0?`rgba(220,193,121,${.09+open*.22})`:pass===1?`rgba(239,232,216,${.26+tighten*.08})`:pass===2?`rgba(255,247,218,${.070+open*.12})`:`rgba(38,49,62,.10)`;ctx.lineWidth=pass===0?15:pass===1?2.4:pass===2?.8:5;ctx.stroke()}if(open>.02){[-1,1].forEach(sign=>{const th=sign*gap/2;const [x,y]=ringPoint(th<0?Math.PI*2+th:th,scale,p);const g=ctx.createRadialGradient(x,y,0,x,y,scale*.18);g.addColorStop(0,`rgba(255,248,218,${.50*open})`);g.addColorStop(.34,`rgba(220,193,121,${.30*open})`);g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(x-scale*.20,y-scale*.20,scale*.40,scale*.40);ctx.beginPath();ctx.arc(x,y,scale*.018,0,Math.PI*2);ctx.fillStyle=`rgba(220,193,121,${.42*open})`;ctx.fill()});if(open>.86){const a=.76*open;ctx.textAlign='center';const titleSize=Math.min(30,Math.max(18,scale*.043));const subSize=Math.min(15,Math.max(11,scale*.024));ctx.font=`italic ${titleSize}px Cormorant Garamond, Georgia, serif`;ctx.fillStyle=`rgba(239,232,216,${.46*a})`;ctx.fillText('The system stopped.',0,scale*.56);ctx.font=`${subSize}px Inter, sans-serif`;ctx.fillStyle=`rgba(220,193,121,${.72*a})`;ctx.fillText('MEMORY PRESERVED',0,scale*.63);ctx.fillStyle=`rgba(170,160,141,${.48*a})`;ctx.fillText('AUTHORITY RETURNED',0,scale*.69)}}ctx.save();ctx.translate(0,scale*.56);ctx.scale(1,.17);for(let i=0;i<6;i++){ctx.beginPath();ctx.arc(0,0,scale*(.22+i*.055),0,Math.PI*2);ctx.strokeStyle=i%3===0?'rgba(220,193,121,.11)':'rgba(239,232,216,.042)';ctx.lineWidth=.7;ctx.stroke()}ctx.restore();ctx.restore()}
function organicNoise(k,t){return Math.sin(k*5.31+t*.00073)*.52+Math.sin(k*11.7+t*.00041+1.8)*.31+Math.sin(k*23.2+t*.00019+2.4)*.17}
function drawBreath(t,cx,cy,scale,p){const appear=smooth(clamp((p-.76)/.24,0,1));if(appear<=.01)return;ctx.save();ctx.translate(cx+mouseX*10,cy+mouseY*7);ctx.globalCompositeOperation='lighter';const isMobile=W<960;const len=scale*(isMobile?.74:.96),start=-len,end=lerp(-len,len,appear);for(let pass=0;pass<3;pass++){ctx.beginPath();for(let i=0;i<=200;i++){const k=i/200,x=lerp(start,end,k);const asym=(k-.5)*scale*.006*Math.sin(t*.00037);const breath=Math.sin(k*Math.PI*3.6+t*.00093)*scale*.009;const living=organicNoise(k,t)*scale*.0055;const y=breath+living+asym;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=pass===0?`rgba(220,193,121,${.13*appear})`:pass===1?`rgba(255,247,218,${.35*appear})`:`rgba(185,157,87,${.23*appear})`;ctx.lineWidth=pass===0?8:pass===1?1.45:.72;ctx.stroke()}ctx.restore()}
function miniDraw(t){mctx.clearRect(0,0,124,28);const g=mctx.createLinearGradient(0,0,124,0);g.addColorStop(0,'rgba(220,193,121,.05)');g.addColorStop(.5,'rgba(220,193,121,.18)');g.addColorStop(1,'rgba(220,193,121,.035)');mctx.fillStyle=g;mctx.fillRect(0,0,124,28);mctx.beginPath();for(let i=0;i<=82;i++){const x=i/82*124,y=14+Math.sin(i*.18+t*.001)*2.4+Math.cos(i*.065)*1.6;if(i===0)mctx.moveTo(x,y);else mctx.lineTo(x,y)}mctx.strokeStyle='rgba(220,193,121,.68)';mctx.lineWidth=1;mctx.stroke();mctx.strokeStyle='rgba(239,232,216,.13)';mctx.strokeRect(.5,.5,123,27)}
function tick(t){const now=performance.now();const frozen=now<freezeUntil;if(!frozen)phase=lerp(phase,target,.065);const p=currentP();const dt=frozen?frozenTime:t;const mobile=W<960;const cx=mobile?W*.67:W*.62,cy=mobile?H*.54:H*.46,scale=Math.min(W*(mobile ? .39 : .255),H*(mobile ? .48 : .70),mobile?310:500);background(cx,cy,scale);drawEchoes(dt,cx,cy,scale,p);drawFormula(dt,cx,cy,scale,p);drawDust(dt,cx,cy,scale,p);drawCoreRing(dt,cx,cy,scale,p);drawBreath(dt,cx,cy,scale,p);miniDraw(dt);requestAnimationFrame(tick)}
addEventListener('resize',()=>{cancelAnimationFrame(resizeRaf);resizeRaf=requestAnimationFrame(resize)});
resize();setPhase(3);requestAnimationFrame(tick);
